### PR TITLE
Update to JNA 4.2.0

### PR DESCRIPTION
**Pull request by gohai**
My fix from a656ad25400d684ba18bb1a299e7157bd2e33178 is now part upstreamed and part of a stable JNA release, so update to this one.

### CODE REVIEW

**Comment by gohai** [comment]
@codeanticode Hope this makes sense to you!

**Comment by benfry** [comment]
Is this going to conflict with the JNA used by the PDE?

**Comment by gohai** [comment]
If it does, it would be an issue with processing-video since 038d80f121679710f4fa7104b930bfac5a866ab8. (Note: the Download Manager is still distributing an even oder version of processing-video currently, so it would only show up for people that get their library from GitHub.)

@benfry Is PDE's JNA used on all platforms? I'll definitely go test those..

**Comment by neilcsmith-net** [comment]
@gohai Have you tested this on Windows at all?  Some issues have been seen with GStreamer-Java on Windows with later versions of JNA.  Would love to know if we can ignore that issue now.  If not, please report at https://github.com/gstreamer-java

@benfry one JNA version per process, so could be OK?

**Comment by codeanticode** [comment]
I tested the video library using JNA 4.2.0 on Windows and Mac OS X, and didn't get any conflict with PDE's JNA.

**Comment by gohai** [comment]
@neilcsmith-net I guess we'll try and revert if needed.

@codeanticode Thanks a lot! Would it be possible to distribute the new version through the Library Manager before the next version is released? Right now I am bundling the updated version with the tar-balls for ARM, as well as the Raspbian images, but it be nicer if folks could just download it as usual through the UI when they need it.

**Comment by codeanticode** [comment]
Ok, here: https://github.com/processing/processing-video/releases/tag/latest

**Pull request merged**
