### PR TITLE
added public getters for playing, paused, repeat

### PR DESCRIPTION
**Pull request by einraum-design**
Would be great, if you can add these getters for the next processing release.

### CODE REVIEW

**Comment by GoToLoop** [comment]
Finally a more sane & direct way to test whether a video has finished playing.  
But I've got a request. For `boolean` getters, it makes more sense to prefix it w/ "is", like **isPlaying()**!

**Comment by einraum-design** [comment]
You're right, it's more processing style (in Minim it's also called isPlaying). I changed the names.

**Comment by AlvaroHermida** [comment]
Is there any reason to keep this urgent patch unmerged during more than three years? Even the requests on the main [processing/processing](https://github.com/processing/processing) repository are being sistematically rejected and sent to this frozen and forgotten dead end, alleging this bug "is a case for processing-video." (see [Movie.isPlaying() #5596](https://github.com/processing/processing/issues/5596)).

Blocking or ignoring good and useful user contributions like this one directly violates the rhetoric ["Please submit all your bug reports and pull requests related to the video library here. Your contribution is really important to keep the Processing project moving forward!"](https://github.com/processing/processing-video#processing-video), and effectively discourages any more contributions.

**Comment by neilcsmith-net** [comment]
@codeanticode just been helping a couple of people on the forum with an issue that would be better dealt with by this (than accessing the PlayBin directly). Could it be considered in v2?

**Comment by AlvaroHermida** [comment]
Thanks!

**Comment by codeanticode** [comment]
You are welcome. The plan is to release a last beta version including all the latest fixes and improvements before pushing the final 2.0 release through the contributions manager.

**Pull request merged**
